"""update embedding dimension to 1024

Revision ID: 2419c470c651
Revises: b6ba9441bac1
Create Date: 2026-03-27 11:24:25.933209
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '2419c470c651'
down_revision: Union[str, Sequence[str], None] = 'b6ba9441bac1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_embeddings', 'embedding',
               existing_type=Vector(dim=1536),
               type_=Vector(dim=1024),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product_embeddings', 'embedding',
               existing_type=Vector(dim=1024),
               type_=Vector(dim=1536),
               existing_nullable=False)
    # ### end Alembic commands ###
